apiVersion: v1
kind: PersistentVolume
metadata:
  name: test1-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "gfs-cluster1"
    path: "test1-data"
